version: '3.1'

services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      DB_HOST: mongo
      DB_BASE: heropa
      DB_PORT: 27017
      DB_USER: root
      DB_PWD: welcome
      PORT: 3000

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: welcome
